### ISSUE TITLE
"Something went wrong. Please try again" after IPS update

### ISSUE THREAD

**Issue by MStruntze** [Lavoaster/IP.Board-Steam-Authentication-Method#58]
After updating to v4.1.14 users are unable to use this sign in method and are met with the ["Something went wrong. Please try again"](https://gyazo.com/9cf36eb8cac49689d35fa63bb27e6585) error.
No errors in system and error logs on ACP.

**Comment by johngalt** [comment]
Can confirm this problem since the v4.1.14 update. Was working fine prior to update. Not seeing any errors aside from what the OP mentioned. Trying to connect the steam account on the Account Settings page just redirects back to the forums as if nothing happened.

**Comment by johngalt** [comment]
I think it has something to do with the recent change in the API with \IPS\Http\Url (https://invisionpower.com/release-notes/4114-r49/). It only shows what was changed to contributors, however.

Doing some debugging, I believe the error is within the validate function, probably with the above mentioned  API change:

`$response = (string)\IPS\Http\Url::external('https://steamcommunity.com/openid/login')->request()->post($params);`

**Comment by madman32395** [comment]
@johngalt good guess, but in the post referenced in that release note (in the contributor chat), the functions utilized in this plugin, are unaffected.

> Rather than a single \IPS\Http\Url class, there are now 3 classes, each of which extends the previous:
\IPS\Http\Url, objects of which are external URLs
\IPS\Http\Url\Internal, objects of which are internal URLs
\IPS\Http\Url\Friendly, objects of which are front-end friendly URLs
You still create objects in the same way (so backwards compatibility is maintained) using ::internal(), ::external(), etc. or there is a new ::createFromString() method to just take a string.


so it's something else, but looking into it.

**Comment by madman32395** [comment]
so far determined its authentication issue.   Soon™  (lol shouldn't take as long as valve though)

**Comment by madman32395** [comment]
Appears that IPS released an update (4.1.14.1) and it was supposed to fix most 3rd party addons. 

> Version 4.1.14.1: This is a small maintenance update to address issues some clients had with certain URLs. We have also seen clients having issues with many third-party plugins and this update will attempt to better capture those errors.

But on my site, I got no change with the plugin. everything in the plugin /should/ work  as nothing is depreciated/removed.

**Comment by MStruntze** [comment]
Updating to the latest version of IPS didn't change anything. Still no error or system logs.

**Comment by NightlyDev** [comment]
Look's like OpenID does not validate... Causing the error.

**Comment by madman32395** [comment]
> Just uploaded the old Url class

oh you're talking about reverting the URL Class back to pre 4.1.14.x   ;;; hmm. i guess that's a hacky workaround, but still is a IPS issue that needs to be addressed.

**Comment by johngalt** [comment]
@NightlyDev 

Mind sending me the old Url class so I can do the same thing?

**Comment by MStruntze** [comment]
They released another update, but the issue seems to persist.

**Comment by Pydrex** [comment]
We can confirm the issue is still happening on the latest update of 4.1.14.2

**Comment by ctark** [comment]
For anyone who wants to use NightlyDev's workaround until the dev is able to resolve this issue, here is an older version of Url.php.  Follow his instructions and you should be fine.  Make sure you don't overwrite the Url.php that is there, make a new file called Urlold.php

**http://pastebin.com/YQ4ZTpLQ**

**Comment by Whip-Tide** [comment]
Hello, I am trying to do this workaround. How exactly do i do this?

**Comment by Lavoaster** [comment]
Hi All,

In the update IPS pushed out, it contained an updated query parser which broke some of the values in being sent by Steam. This change meant that the plugin was sending wrong values back over to steam's service and steam was unable to verify a valid request was made to login to the system, so it returned false.

A quick fix for this will be to update `system\Http\Url.php` find line `1064` and replace 

```
$keyAndValue = explode( '=', $part );
```
with
```
$keyAndValue = explode( '=', $part, 2 );
```
---- Diff
```diff
-$keyAndValue = explode( '=', $part );
+$keyAndValue = explode( '=', $part, 2 );
```

**Comment by Lavoaster** [comment]
Here's a link to the bug I've posted on the IPS Tracker.

https://invisionpower.com/4bugtrack/active-reports/url-query-string-parsing-is-too-aggressive-strips-extra-from-urls-breaks-openid-r12395/

**Comment by jimjim135** [comment]
Thanks for the update, Lavoaster.

I've made the changes you've suggested on line 1064 and I'm still experiencing the same result.

Do you have any other suggestions? Thank you.

**Comment by madman32395** [comment]
Can confirm what @jimjim135 said.

**Comment by aStonedPenguin** [comment]
Doesn't seem to fix the issue on PHP7

**Comment by madman32395** [comment]
Penguin. Im on php7 and the edit lavo posted works fine.

**Comment by aStonedPenguin** [comment]
Anyone who needs it can find the old url class here: https://gist.github.com/aStonedPenguin/1e454ee0b930e5f0cf34977dd47518a4

**Comment by madman32395** [comment]
Upon doing lavo's fix, and reverting any changes made by previous "workarounds". it should work to login to the suite on the frontend. 

also just a heads up distributing the oldclass (or any part of the suite) is against IPS's SOS anyway.

**Comment by Master96Pro** [comment]
@jimjim135 same problem here. I can't sign in on the cp through steam :(

**Comment by MrEichi** [comment]
Can confirm that lavos fix in the URL class solves it. GG IPS Team :(

**Comment by Nesyth** [comment]
Updating to the newest beta version of 4.1.15 fixes the issue.

**Comment by madman32395** [comment]
The fix was done one the other ticket. It was deemed ips issue. And set to
fix on 4.1.15

**Comment by madman32395** [comment]
I'm mobile so I can't edit my last post lol. But the other ticket is referring to this one.

I'll add a thing to this ticket saying it was fixed by IPS.

**Comment by Celant** [comment]
Hey @madman32395 currently we're unable to upgrade our IPS. We've applied the hotfix that lavo mentioned which worked perfect for the website front-end.

Our issue now is the admincp. Still getting "Something went wrong. Please try again." when attempting to login with Steam via the AdminCP. Any ideas?

Happy to provide a phpinfo(); dump if needed.

**Comment by Flumadiddle** [comment]
I am still receiving this same error. I have reinstalled the plugin multiple times.
I am running IPB v4.1.15 on nginx 7.0.

**Comment by Flumadiddle** [comment]
Even with Friendly URLs and rewrites disabled, the issue is still occurring. I am running the latest versions of both IPB w/ unmodified Url.php and the plugin.

**Comment by stormdr1ve** [comment]
It works correctly on 4.1.15 on PHP7 and nginx for me, tunneling the request directly to PHP without rewriting the (friendly) url.

**Comment by Aszune** [comment]
I have **Nginx** and **PHP 5.6**, with **IPS 4.1.15**, I have the same issue @Flumadiddle 
The same error, when steam redirect to my forum, I see error message, and the account not linked.

"Something went wrong. Please try again"

What configuration have you @stormdr1ve ?

**Comment by aStonedPenguin** [comment]
Using the old URL class fixes the issues you guys are having now.

**Comment by madman32395** [comment]
are you guys using the version available here or the one from the IPS Marketplace? Try uploading the one from the marketplace and see if that helps.

**Comment by Aszune** [comment]
I download and using the plugin from Marketplace  @madman32395

**Comment by Lavoaster** [comment]
Anyone trying to use ACP authentication, can you download [this](https://raw.githubusercontent.com/Lavoaster/IP.Board-Steam-Authentication-Method/master/upload/system/Login/Steam.php) and replace the file at `system\Login\Steam.php`

**Comment by Flumadiddle** [comment]
@madman32395 
Looks like you were right! The nginx rewrites I had configured were not taking care of query strings correctly. I fixed them and the plugin is now working properly.

Old rewrite rules:
```
        location / {
            try_files  $uri $uri/ /index.php;
        }
        location ~^(/page/).*(.php)$ {
            try_files  $uri $uri/ /index.php;
        }
```
New rewrite rules:
```
        location / {
            try_files $uri $uri/ /index.php?$args;
        }
```

**Comment by deathward4** [comment]
The updated Steam.php file worked. AdminCP is accessible now.

You're wonderful.

**Comment by Aszune** [comment]
Thank you @Flumadiddle, I apply new rewrite rules, u posted here, and now works for me!
